### ISSUE TITLE
maybe if typst's version above 0.7,there is a bug about counter of affiliation_counter

### ISSUE THREAD

**Issue by Schweik7** [mrwunderbar666/typst-apa7ish#1]
in my pc,first affiliation's number is "-",not "a"; second affiliation's number is "a",not `"b".

so i moved counter's step award
```typst
affiliations [
      #affiliation_counter.step()
      #super(affiliation_counter.display("a"))#h(1pt)#emph(affiliation)  
```

**Comment by mrwunderbar666** [comment]
Thanks for catching that!

I've implemented less hacky solution by updating the counter to 1
