### ISSUE TITLE
Multiple Affiliations per author

### ISSUE THREAD

**Issue by LeSasse** [mrwunderbar666/typst-apa7ish#2]
Thank you for the cool template. I tried it out and realised that while it nicely groups authors with the same affiliation, it does not seem to allow authors to have multiple affiliations. Is there a way to implement this, for example something like:

```
      (name: "Niklas Luhmann",
      affiliation: ["University of Pennsylvania", "Research Center Somewhere"],
      orcid: "0000-1111-1111-1111")
```

**Comment by mrwunderbar666** [comment]
Thanks for the issue. You're right, multiple affiliations are currently not supported. Will add this for the next version

**Comment by mrwunderbar666** [comment]
@LeSasse, I added this feature with the latest commit (19df400). You can either use the latest version directly here from github or wait until my pull request (typst/packages#1202) was approved and the update propagated to the typst universe.
Note that you have to update your import statements as well:
```typst
#import "@preview/apa7-ish:0.2.0": *
```

**Comment by LeSasse** [comment]
Thanks for the quick implementation! Will clone it from here as I write locally.
